### ISSUE TITLE
Unicode Chinese Characters (ttf) are not being shown

### ISSUE THREAD

**Issue by Shum88** [aviks/GameZero.jl#67] opened 2023-03-25 04:39 UTC
#sf = SDL2.TTF_RenderText_Blended(font, text, SDL2.Color(color...))
    sf = SDL2.TTF_RenderUTF8_Blended(font, text, SDL2.Color(color...))

Following Aviks suggestion as above ...

Chinese Characters can be shown correctly
![SnakeZero_01](https://user-images.githubusercontent.com/3876605/227696430-0ee2918e-f223-4d4b-98e2-31b498468397.jpg)
![SnakeZero_02](https://user-images.githubusercontent.com/3876605/227696439-2b6e1608-a9de-4ae0-822a-950b8c81c2ce.jpg)

**Comment by Shum88** [comment] 2023-03-25 04:41
if gameover == false
        display = "分數(Score) = $score"
    else
        display = "GAME OVER! Final Score = $score"
        #play again instructions
        replay = TextActor("Click to play Again,  點擊...再玩", sDspFont; font_size = 26, color = Int[0, 0, 0, 255])
        replay.pos = (135, 390)
        draw(replay)
    end

**Comment by aviks** [comment] 2023-03-25 22:40
duplicate of #66. Closed by #68

**Closed by aviks** 2023-03-25 22:40 UTC
